spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sb3?currentSchema=sb3,sb5
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8080

# Log4j2 configs
logging:
  # Path to log4j2.xml
  config: ${LOGGING_CONFIG:classpath:log4j2.xml}

sb3:
  method-security:
    enabled: false
  jwt:
    expireDuration: 3600000
    secretKey: ThisIsSecretKey
